### ISSUE TITLE
Mobile site issues

### ISSUE THREAD

**Issue by KVanSant** [KVanSant/brunch-and-booze#27]
Background image:
Background image does not display properly on mobile, especially when trying to type into the search field. The image no longer covers the whole background.

Not found message:
The error message for when an item is "not found" display poorly on mobile. I think this needs to be displayed differently, possibly with a modal. Open to ideas.

Mobile design:
I'm not completely sold on the mobile design now that I'm seeing it live. Thinking of redesigning it.

**Comment by KVanSant** [comment]
@clln Some issues I'm having with mobile design are above. I'd love your feedback and thoughts whenever you have a chance!

**Comment by ghost** [comment]
@KVanSant I think the bg issue might be due to it being on the `:after` pseudo property instead of on the body directly. Though I see you did that so that you could get the opacity. You could either apply the opacity to the image directly or we can play with the CSS to get it just right.

I agree the "not found" message needs to be updated for better usability. It actually took me a few attempts to realize the message was appearing below the search boxes and I had to scroll. With the current design, a modal would be the most prominent. I think that could be the way to go.

As for the design, I think the title and tagline take up a lot of screen real estate. You can get away with making them smaller. Also, you could attempt to make the mobile version feel more like a native app. Like, the first page could be a nav menu of sorts that takes the user to

Search
Recipes
Account

Where search takes them to a new screen and the user doesn't need to see the title or tagline at all. It's a lot more work, but just a possibility. Trying to stir the idea pot. :)

**Comment by KVanSant** [comment]
@clln Ahh yes I did think it probably had to something to do with :after property. I used that because when I was changing the opacity before it was affecting the text on the page too, and this was one way I found that someone was able to get around it. I had thought of applying the opacity to the image directly in Photoshop or Illustrator anyways to clean up some CSS, so I'll do that today and hopefully it will fix the background image issues.

For the "not found" message modal it is! 

You must be reading my mind. I did want the mobile version to feel more app like.  I do like this idea a lot of having a nav menu being the first thing the user sees so I shall play around with that. Hmmmm.

Looks like I have a plan for today then. I'll be working on all of the above in that same order.

Thank you thank you! I'm always open to idea pot stirrings.
